import Questao from "@/components/Questao";
import RespostaModel from "@/model/resposta";
import QuestaoModel from "@/model/questao";
import Head from "next/head";

export default function Home() {

  const questaoTeste = new QuestaoModel(1, 'Melhor Cor?', [
    RespostaModel.errada('verde'),
    RespostaModel.errada('vermelha'),
    RespostaModel.errada('azul'),
    RespostaModel.certa('preta')
  ])

  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Questao valor={questaoTeste}/>
      </main>
    </>
  );
}
