import Questao from "@/components/Questao";
import RespostaModel from "@/model/resposta";
import QuestaoModel from "@/model/questao";
import Head from "next/head";
import { useState } from "react";

const questaoMock = new QuestaoModel(1, 'Melhor Cor?', [
  RespostaModel.errada('verde'),
  RespostaModel.errada('vermelha'),
  RespostaModel.errada('azul'),
  RespostaModel.certa('preta')
])

export default function Home() {

  const [questao, setQuestao] = useState(questaoMock)

  function respostaFornecida(indice: number){
    setQuestao(questao.responderCom(indice))
    console.log(indice)
  }

  function tempoEsgotado(){

    if(!questao.respondida){
      setQuestao(questao.responderCom(-1))
    }
  }

  return (
    <>
      <Head>
        <title>Quiz</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Questao valor={questao}
          respostaFornecida={respostaFornecida}
          tempoEsgotado={tempoEsgotado}
        />
      </main>
    </>
  );
}
